server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.52.128:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: 192.168.52.128
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS

# LangChain4j OpenAI配置
langchain4j:
  openai:
    api-key: sk-59780e0e6e4c47eb96a9c372bef197d9
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    model-name: deepseek-v3

# 线程池配置
thread-pool:
  cache-rebuild:
    core-size: 5        # 核心线程数
    max-size: 10        # 最大线程数
    queue-capacity: 100 # 队列容量
  seckill-order:
    core-size: 3        # 核心线程数（消费者数量）